version: "3.8"

services:
  twinkly-clock:
    build: .
    container_name: twinkly-clock
    network_mode: host
    restart: always
    environment:
      - TZ=UTC                      # Set your timezone, e.g. Australia/Sydney
      - TWINKLY_IP=192.168.1.100    # Set your Twinkly device IP
    volumes:
      - ./config:/app/config
